### ISSUE TITLE
ModuleNotFoundError: No module named 'RNA'

### ISSUE THREAD

**Issue by STF003** [pnatsi/StarSeeker#1]
Hi

When I use StarSeeker, the program prompts me **ModuleNotFoundError: No module named'RNA'**.
and I use pip install RNA，but I got the same error，
What should I do?
Thanks a lot.

**Comment by pnatsi** [comment]
Hi,

You need to install the ViennaRNA package

**Comment by aisangekoukou** [comment]
> Hi,
> 
> You need to install the ViennaRNA package

**Comment by STF003** [comment]
Hi
I have solved my problem, thank you, StarSeeker is really amazing and solved my big trouble.
